### ISSUE TITLE
Load time jumps 2000ms after installing

### ISSUE THREAD

**Issue by TheRealNate** [dropfen/meteor-app-loader#1]
Hello.

My total load time jumps by 2000ms after installation

**Comment by dropfen** [comment]
Hmm, this is interesting.
Please explain how you are measuring it, thx.

**Comment by TheRealNate** [comment]
Hitting F12 in Google Chrome and clicking "Network".
Before Install (Roughly):
4000ms
6000ms
4000ms
4000ms
4000ms
After Install(Roughly):
6000ms
6000ms
6000ms
6000ms
6000ms

**Comment by dropfen** [comment]
I just tested it with a plain project, and yes it needs a bit more time for the initial rendering, but it was not more then 100ms, in my case.
